filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log


filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true


processors:
- add_docker_metadata: ~


setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"


output.elasticsearch:
  hosts: ["https://es01:9200"]
  username: "elastic"
  password: "changeme"
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"